// This file is "main.dart"
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'user_model.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'user_model.g.dart';

@freezed
class UserModel with _$UserModel {
  const factory UserModel({
    @JsonKey(name: "username") String? username,
    @JsonKey(name: "uid") String? uid,
    @JsonKey(name: "email") String? email,
    @JsonKey(name: "bio") String? bio,
    @JsonKey(name: "followers") List? followers,
    @JsonKey(name: "following") List? following,
    @JsonKey(name: 'photoAvatarUrl') String? photoAvatarUrl,
    @JsonKey(name: 'fcmToken') String? fcmToken,
  }) = _UserModel;

  factory UserModel.fromJson(Map<String, Object?> json) =>
      _$UserModelFromJson(json);

  factory UserModel.fromDocumentSnapshot(
      DocumentSnapshot<Map<String, dynamic>?>? dataSnapshot) {
    final data = dataSnapshot!.data();

    return UserModel(
        uid: data!['uid'],
        username: data['username'],
        email: data['email'],
        bio: data['bio'],
        followers: data['followers'],
        following: data['following'],
        fcmToken: data['fcmToken'],
        photoAvatarUrl: data['photoAvatarUrl']);
  }
}
