// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'user_model.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'user_model.g.dart';

@freezed
class UserModel with _$UserModel {
  @JsonSerializable()
  const factory UserModel(
      {@JsonKey(name: "username") String? username,
      @JsonKey(name: "uid") String? uid,
      @JsonKey(name: "email") String? email,
      @JsonKey(name: "bio") String? bio,
      @JsonKey(name: "followers") List? followers,
      @JsonKey(name: "following") List? following,
      @JsonKey(name: 'photoAvatarUrl') String? photoAvatarUrl}) = _UserModel;

  factory UserModel.fromJson(Map<String, Object?> json) =>
      _$UserModelFromJson(json);
}
