// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCssLcs-kmXLgILAXCsptNcL7pqqkGTuZU',
    appId: '1:61936790495:web:a89ff524cd660fd119326a',
    messagingSenderId: '61936790495',
    projectId: 'instagramclone-fb91b',
    authDomain: 'instagramclone-fb91b.firebaseapp.com',
    storageBucket: 'instagramclone-fb91b.appspot.com',
    measurementId: 'G-B58XGKZH0R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfGeNumAgLlkPbLjxEFQUnvOc4JKVzXgI',
    appId: '1:61936790495:android:05d12a2e43daa24e19326a',
    messagingSenderId: '61936790495',
    projectId: 'instagramclone-fb91b',
    storageBucket: 'instagramclone-fb91b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcW_1wDWg5M-tPVJhOsCIe4PrPvPGsX9Q',
    appId: '1:61936790495:ios:4c07fd1173d5846f19326a',
    messagingSenderId: '61936790495',
    projectId: 'instagramclone-fb91b',
    storageBucket: 'instagramclone-fb91b.appspot.com',
    iosClientId: '61936790495-oi9g5a89cco18q587hllnib0881utn81.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcW_1wDWg5M-tPVJhOsCIe4PrPvPGsX9Q',
    appId: '1:61936790495:ios:4c07fd1173d5846f19326a',
    messagingSenderId: '61936790495',
    projectId: 'instagramclone-fb91b',
    storageBucket: 'instagramclone-fb91b.appspot.com',
    iosClientId: '61936790495-oi9g5a89cco18q587hllnib0881utn81.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramClone',
  );
}
